title: RSS News and political commentary and critique from the Intellectual Dark Web.
author: Cale McCollough
email: info@cookingwithcale.org # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  Real Simple News is Really Simple Syndication (RSS) news and political commentary and critique from the Intellectual Dark Web hosted by Cale McCollough, Captain of the Kabuki Starship and technology pioneer.
baseurl: "/"
url: "https://realsimplenews.net"
twitter_username: RSSCommentary
github_username:  RealSimpleNews
instagram_username: CaleMcCollough
social:
  name: Cale McCollough
  links:
    - https://twitter.com/CaleMcCollough
    - https://www.linkedin.com/in/CaleMcCollough
    - https://github.com/KabukiStarship

disqus:
  shortname: realsimplenews

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: real-simple-news
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - real-simple-news.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
