title: RSS News and political commentary and critique from the Intellectual Dark Web.
author: Cale McCollough
email: info@rsscommentary.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  RSS Commentary is Really Simple Syndication (RSS) news and political commentary and critique from the Intellectual Dark Web hosted by Cale McCollough.
baseurl: "/"
url: "https://rsscommentary.com"
twitter_username: RSSCommentary
github_username:  RSSCommentary
periscope_username:  RSSCommentary
instagram_username: RSSCommentary
social:
  name: RSS Commentary
  links:
    - https://twitter.com/RSSCommentary
    - https://github.com/RSSCommentary
    - https://www.linkedin.com/in/CaleMcCollough

disqus:
  shortname: realsimplenews

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: rsscommentary
exclude:
  - ReadMe.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - rsscommentary.png
  - bug_report_template.md
  - code_of_conduct.md
  - contributing.md
  - feature_request_template.md
  - issue_template.md
  - pull_request_template.md
  - roadmap.md

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
